# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('owed_to', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('uniqueid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debt_tracker.Debtor'),
        ),
    ]
