# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='stauts',
            field=models.CharField(default='Not Paid', max_length=15),
        ),
    ]
