# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt_tracker', '0002_debt_stauts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='stauts',
            new_name='status',
        ),
    ]
