# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt_tracker', '0003_auto_20170620_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtor',
            old_name='debtor',
            new_name='name',
        ),
    ]
