# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_tracker', '0004_auto_20170621_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=30)),
            ],
        ),
    ]
